
services:
  server:
    image: srv
    build: tcp_to_tun/src
    networks:
      - tcp-tunnel
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

  client:
    image: cli
    build: tun_to_tcp/cli
    networks:
      - tcp-tunnel
    depends_on:
      - server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
  
networks:
  tcp-tunnel:
    driver: bridge
